name: location_picker
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  osm_nominatim: ^3.0.1
  geoflutterfire_plus: ^0.0.31
  cloud_firestore: ^5.4.4
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
